### ISSUE TITLE
Currently working on...

### ISSUE THREAD

**Issue by jinpyojeon** [binay-jana/RoboticsContestScoringSystem#7]
Hi! I didn't know where to put my current progress, so I'll place it here.

So I have been working on the reducing the number of Bootstrap columns (which is taking more time than I anticipated) and the method to calculate the score. 

I am thinking of placing the score into the columns of the run data, but I'll have to revamp my method function to take in data directly from the POST request. Should I do that?

I think I need to stash away the display part to finish later to do the Javascript part (or possibly done with Bootstrap?), as the random assignment is a crucial part of the program. 

Once I am done with the last of my exams this week, I'll make sure to put more effort in.

**Comment by binay-jana** [comment]
yeah sure. I will give you a call after you are done with your exams.
